# Generated by Django 4.0.2 on 2022-02-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carprice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('value', models.IntegerField(max_length=50, verbose_name='value')),
            ],
        ),
    ]
